#!/usr/bin/env bash
set -euo pipefail

tmux_control_mode_args=()

export TMUX_TASKLOOP_MAIN_REPORT=next

while (( $# > 0 )); do
	case "$1" in
	-d|--debug)
		export TMUX_TASKLOOP_DEBUG=Yes
		shift
		;;
	-C|--control)
		tmux_control_mode_args=(-C)
		shift
		;;
	-o|--one)
		export TMUX_TASKLOOP_ONE_REPORT=Yes
		shift
		;;
	-r|--report)
		TMUX_TASKLOOP_MAIN_REPORT="$2"
		shift 2
		;;
	-r*)
		TMUX_TASKLOOP_MAIN_REPORT="${1#-r}"
		shift
		;;
	--report=*)
		TMUX_TASKLOOP_MAIN_REPORT="${1#--report=}"
		shift
		;;
	-d*|-C*|-o*)
		set -- "-${1: 1:1}" "-${1: 2}" "${@: 2}"
		;;
	*)	echo "Unexpected argument $1" >&2
		exit 64  # EX_USAGE
		;;
	esac
done

exec tmux \
	-L tmux-taskloop-$$ \
	"${tmux_control_mode_args[@]}" \
	start-server \; \
	source-file tmux-taskloop.conf
