{
  imports = [
    ./channels.nix
    ./jellyfin.nix
    ./framework-rfkill.nix
    ./mailutils.nix
    ./mosh.nix
    ./nginx.nix
    ./nix-builder.nix
    ./nix-cache.nix
    ./nixbuild.net.nix
    ./openvpn.nix
    ./pd
    ./phone-backup.nix
    ./pi.nix
    ./postfix.nix
    ./rclone.nix
    ./scantoonedrive.nix
    ./servegnucash.nix
    ./sudo.nix
    ./syncthing.nix
    ./taskserver
    ./user.nix
    ./winapps.nix
    ./wsl.nix
  ];
}
