{
  imports = [
    ./channels.nix
    ./hyperv.nix
    ./jellyfin.nix
    ./mail.nix
    ./mosh.nix
    ./nginx.nix
    ./nix-cache.nix
    ./pd
    ./phone-backup.nix
    ./pi.nix
    ./scantoonedrive.nix
    ./sudo.nix
    ./syncthing.nix
    ./taskserver
    ./time-sync.nix
    ./user.nix
    ./wsl.nix
  ];
}
