{
  imports = [
    ./framework-rfkill.nix
    ./mailutils.nix
    ./nginx.nix
    ./nhgc.nix
    ./nix-builder.nix
    ./nix-cache.nix
    ./nixbuild.net.nix
    ./openvpn.nix
    ./pd
    ./pi.nix
    ./postfix.nix
    ./rclone.nix
    ./sudo.nix
    ./syncthing.nix
    ./user.nix
  ];
}
