name: CI checks
on:
  - push
  - pull_request

jobs:
  eval:
    name: Check evaluation
    # Trigger CI when either (a) a commit is pushed (which implicitly excludes
    # pushes from GitHub Actions) or (b) there's a pull request created by
    # GitHub Actions.
    if: github.event_name == 'push' || github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          github-token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
      - name: Set up Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@v14
      - name: Check evaluation
        run: nix flake check --no-build --all-systems --keep-going

  formatting:
    name: Check formatting
    # Trigger CI when either (a) a commit is pushed (which implicitly excludes
    # pushes from GitHub Actions) or (b) there's a pull request created by
    # GitHub Actions.
    if: github.event_name == 'push' || github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          github-token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
      - name: Set up Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@v14
      - name: Check formatting
        run: nix fmt -- --ci

  build:
    name: Build check derivations
    # Trigger CI when either (a) a commit is pushed (which implicitly excludes
    # pushes from GitHub Actions) or (b) there's a pull request created by
    # GitHub Actions.
    if: github.event_name == 'push' || github.actor == 'github-actions[bot]'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm

    steps:
      - name: Recover runner disk space
        uses: wimpysworld/nothing-but-nix@v10
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          github-token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
      - name: Set up Nix caching
        uses: DeterminateSystems/magic-nix-cache-action@v14
      - name: Run checks
        run: nix run .#nix-run-available-checks -- --github
