name: CI checks
on:
  - push
  - pull_request

jobs:
  eval:
    name: Check evaluation
    # Trigger CI when either (a) a commit is pushed (which implicitly excludes
    # pushes from GitHub Actions) or (b) there's a pull request created by
    # GitHub Actions.
    if: github.event_name == 'push' || github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
      - name: Check evaluation
        run: nix flake check --no-build --all-systems --keep-going

  formatting:
    name: Check formatting
    # Trigger CI when either (a) a commit is pushed (which implicitly excludes
    # pushes from GitHub Actions) or (b) there's a pull request created by
    # GitHub Actions.
    if: github.event_name == 'push' || github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
      - name: Check formatting
        run: nix fmt -- --ci

  build:
    name: Build check derivations
    # Trigger CI when either (a) a commit is pushed (which implicitly excludes
    # pushes from GitHub Actions) or (b) there's a pull request created by
    # GitHub Actions.
    if: github.event_name == 'push' || github.actor == 'github-actions[bot]'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm

    steps:
      - name: Recover runner disk space
        uses: wimpysworld/nothing-but-nix@v10

      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up keys
        env:
          NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          sudo mkdir -p /root/.ssh
          printf '%s\n' "$SSH_KEY" | sudo sh -c 'umask 0077 && tee /root/.ssh/id_ed25519' >/dev/null

          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_KEY" | sh -c 'umask 0077 && tee ~/.ssh/id_ed25519' >/dev/null

          sudo mkdir -p /etc/nix
          printf '%s\n' "$NIX_SIGNING_KEY" | sudo sh -c 'umask 0077 && tee /etc/nix/key' >/dev/null

      - name: Install Nix
        uses: cachix/install-nix-action@v31.11.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
          extra_nix_config: |
            extra-trusted-public-keys = ${{ vars.NIX_EXTRA_TRUSTED_PUBLIC_KEYS }}
            secret-key-files = /etc/nix/key

      # Sometimes a substituter is offline.  That shouldn't cause the builds to
      # fail.
      - name: Set substituters
        env:
          NIX_EXTRA_SUBSTITUTERS: ${{ vars.NIX_EXTRA_SUBSTITUTERS }}
        run: |
          available_substituters=()
          for s in $NIX_EXTRA_SUBSTITUTERS; do
              if nix store info --store "$s"; then
                  available_substituters+=("$s")
              fi
          done

          if (( "${#available_substituters[*]}" > 0 )); then
              NIX_CONFIG="${NIX_CONFIG:+"$NIX_CONFIG"$'\n'}extra-substituters = ${available_substituters[*]}"
              {
                  echo 'NIX_CONFIG<<EOF'
                  printf '%s\n' "$NIX_CONFIG"
                  echo EOF
              } >>"$GITHUB_ENV"
          fi

      - name: Run checks
        run: |
          mkdir -p results
          nix build --out-link results/nix-run-available-checks .#nix-run-available-checks
          nix run .#nix-run-available-checks -- --github --add-root results/result

      - name: Deploy build results
        if: always()
        env:
          DEPLOY_TARGETS: ${{ vars.NIX_DEPLOY_TARGETS }}
        run: |
          if [[ ! -e results ]]; then
            # Results directory wasn't even created, so quit now
            exit 0
          elif ! command -v nix >/dev/null; then
            # Nix failed to install, so quit now
            exit 0
          fi

          ls -Al results

          mapfile -d '' -t build_results < <(find results -type l -printf '%l\0')
          wait "$!" # Check return code from find

          if (( ${#build_results[*]} == 0 )); then
            # Nothing to upload
            exit 0
          fi

          for t in $DEPLOY_TARGETS; do
            nix copy --to "$t" "${build_results[@]}"
          done
