name: Check package builds
on: [push, pull_request]
jobs:
  get-packages:
    name: Get package names
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Work out package list
        id: packages
        run: |
          delim="$(uuidgen)"
          exec >"$GITHUB_OUTPUT"
          printf 'packages<<%s\n' "$delim"
          nix-instantiate --eval --json -E 'builtins.attrNames (import ./pkgs {})'
          printf '%s\n' "$delim"

  build-packages:
    name: Build packages
    needs: get-packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.get-packages.outputs.packages) }}
        channel:
          - nixos-24.05
          - nixos-24.05-small
          - nixos-unstable
          - nixos-unstable-small
          - nixpkgs-unstable
          - null
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: sandbox = relaxed
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Store Nix channel to use
        if: matrix.channel != null
        env:
          CHANNEL: ${{ matrix.channel }}
        run: |
          printf 'NIX_PATH=nixpkgs=channel:%s\n' "$CHANNEL" >>$GITHUB_ENV
      - name: Build ${{ matrix.package }}
        env:
          PACKAGE: ${{ matrix.package }}
        run: |
          nix-instantiate --eval --json -E '(import <nixpkgs> {}).lib.version' |
              jq -r '"Nixpkgs version: \(.)"' >&2
          nix-build pkgs -A "$PACKAGE" -I nixpkgs-overlays="$PWD"/overlays
