name: Style checker
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v20
      - name: Check style
        run: ./style.sh
