name: Style checker
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Run alejandra
        run: nix-shell -p findutils -p alejandra --run 'find . -path ./git -prune -o -type f -name "*.nix" -exec alejandra -c {} +'
