name: Update packages

on:
  schedule:
    - cron: "31 14 * * 0" # Weekly, randomly chosen
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31.11.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          # TODO Remove the need for package updates to need access to my
          # private repositories.
          github_access_token: ${{ secrets.CI_REPO_ACCESS_TOKEN }}
      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update packages
        env:
          GH_TOKEN: ${{ github.token }}
        run: nix run .#nix-update-packages -- --push --pr --use-local
